[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[rpc_endpoints]
avalanche = "https://api.avax.network/ext/bc/C/rpc"
fuji = "https://api.avax-test.network/ext/bc/C/rpc"
arbitrum = "https://arb1.arbitrum.io/rpc"

[etherscan]
avalanche = { key = "${SNOWTRACE_API_KEY}", chain = "avalanche" }
fuji = { key = "${SNOWTRACE_API_KEY}", chain = "fuji" }
arbitrum_one = { key = "${ARBISCAN_KEY}", chain = "arbitrum" }

[fmt]
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config